// SPDX-License-Identifier: LicenseRef-Snap-CD-Source-Available-1.1
// Copyright (c) 2026 Karl Schriek / Schrieksoft.
// No license is granted to use this file, in whole or in part, (a) as training, fine-tuning, retrieval, or
// embedding data for any machine-learning model, or (b) as input to any machine-learning model, agent, or automated
// system for the purpose of producing a derivative work or reimplementation that is not otherwise permitted by the
// Snap CD Source-Available License (including any Competing Product as defined therein). Contact info@snapcd.io
// for terms covering either use.

using System.Reflection;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SnapCd.Contracts;
using SnapCd.Contracts.Mcp;

namespace SnapCd.Generators;

/// <summary>
/// Codegen that emits MCP tool / resource wrappers for every controller action annotated with
/// <c>[ExposeAsMcpTool]</c> or <c>[ExposeAsMcpResource]</c>. Driven by <see cref="McpCommand"/> as a
/// one-shot CLI — writes <c>&lt;ControllerName&gt;McpSurface.cs</c> files into a tracked output
/// folder under the target project.
///
/// Discovery reflects over the already-compiled SnapCd.Server.Core assembly (a project reference, so the
/// shared generator build has produced it anyway) instead of re-compiling the project through a Roslyn
/// workspace:
///   - Walks every concrete type deriving from <see cref="ControllerBase"/>.
///   - For each, collects action methods marked with <c>[ExposeAsMcpTool]</c> / <c>[ExposeAsMcpResource]</c>
///     — including methods inherited from a generic base controller (e.g. <c>GenericCrudController</c>).
///   - The derived controller's <c>[McpEntity]</c> attribute supplies the entity name for the
///     convention-derived descriptions (<see cref="EndpointDocConvention"/>); an [EndpointSummary]
///     on the action overrides the convention, and the annotation's <c>Instructions</c> is appended.
///
/// The single piece reflection cannot provide — the literal <c>Service.Foo(args)</c> call inside each action
/// body — comes from a syntax-only parse of the controller sources (<see cref="ControllerSyntaxIndex"/>).
/// </summary>
public static class McpSurfaceEmitter
{
    /// <summary>
    /// SnapCd license header + auto-generated banner. Prepended to every generated <c>*.g.cs</c>
    /// file because pre-commit's license-header check skips <c>.g.cs</c> (assumes they're
    /// generated-and-already-headed), so the codegen owns the header itself.
    /// </summary>
    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("// SPDX-License-Identifier: LicenseRef-Snap-CD-Source-Available-1.1");
        sb.AppendLine("// Copyright (c) 2026 Karl Schriek / Schrieksoft.");
        sb.AppendLine("// No license is granted to use this file, in whole or in part, (a) as training, fine-tuning, retrieval, or");
        sb.AppendLine("// embedding data for any machine-learning model, or (b) as input to any machine-learning model, agent, or automated");
        sb.AppendLine("// system for the purpose of producing a derivative work or reimplementation that is not otherwise permitted by the");
        sb.AppendLine("// Snap CD Source-Available License (including any Competing Product as defined therein). Contact info@snapcd.io");
        sb.AppendLine("// for terms covering either use.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by SnapCd.Generators. Re-run `dotnet run --project generators/SnapCd.Generators -- mcp`");
        sb.AppendLine("// after changing controller annotations or [EndpointSummary] texts. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using ModelContextProtocol.Server;");
        sb.AppendLine();
    }

    public sealed record GeneratedFile(string FileName, string Source);

    /// <summary>
    /// Walks the assembly, finds every concrete annotated controller, and yields a
    /// <see cref="GeneratedFile"/> for each. The caller writes them to disk.
    /// </summary>
    public static IEnumerable<GeneratedFile> Emit(Assembly assembly, ControllerSyntaxIndex syntaxIndex)
    {
        foreach (var controller in assembly.GetTypes()
                     .Where(t => t.IsClass && typeof(ControllerBase).IsAssignableFrom(t))
                     .OrderBy(t => t.Name, StringComparer.Ordinal))
        {
            if (controller.IsAbstract) continue;
            if (controller.IsGenericType) continue;

            // Require [McpEntity] as the explicit opt-in. Without it, a derived controller that
            // inherits annotated actions from a generic base would still be auto-exposed —
            // bypassing the safety of opt-in.
            var entity = ResolveEntity(controller);
            if (entity is null) continue;

            var actions = CollectAnnotatedActions(controller).ToList();
            var toolActions = actions.Where(a => a.ToolAttribute is not null).ToList();
            var resourceActions = actions.Where(a => a.ResourceAttribute is not null).ToList();

            if (toolActions.Count > 0)
                yield return new GeneratedFile(
                    $"{controller.Name}McpSurface.g.cs",
                    EmitSurface(controller, toolActions, entity, syntaxIndex));

            if (resourceActions.Count > 0)
                yield return new GeneratedFile(
                    $"{controller.Name}McpResourceSurface.g.cs",
                    EmitResourceSurface(controller, resourceActions, entity, syntaxIndex));
        }
    }

    /// <summary>
    /// Walks the inheritance chain and collects every method annotated with
    /// <c>[ExposeAsMcpTool]</c> or <c>[ExposeAsMcpResource]</c>.
    /// </summary>
    private static IEnumerable<AnnotatedAction> CollectAnnotatedActions(Type controller)
    {
        var seen = new HashSet<string>();
        for (var t = controller; t is not null; t = t.BaseType)
        {
            foreach (var member in t.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly))
            {
                if (member.IsSpecialName) continue;
                if (!seen.Add(member.Name)) continue; // a derived override masks the base

                var toolAttr = member.GetCustomAttribute<ExposeAsMcpToolAttribute>(inherit: false);
                var resourceAttr = member.GetCustomAttribute<ExposeAsMcpResourceAttribute>(inherit: false);
                if (toolAttr is null && resourceAttr is null) continue;

                yield return new AnnotatedAction(member, toolAttr, resourceAttr);
            }
        }
    }

    private static McpEntityInfo? ResolveEntity(Type controller)
    {
        for (var t = controller; t is not null; t = t.BaseType)
        {
            var attr = t.GetCustomAttribute<McpEntityAttribute>(inherit: false);
            if (attr is null) continue;
            if (attr.Singular is null || attr.Plural is null) continue;
            return new McpEntityInfo(attr.Singular, attr.Plural);
        }
        return null;
    }

    private static string EmitResourceSurface(Type controller, List<AnnotatedAction> actions, McpEntityInfo? entity, ControllerSyntaxIndex syntaxIndex)
    {
        var ns = controller.Namespace!;
        var className = $"{controller.Name}McpResourceSurface";
        var sb = new StringBuilder();
        EmitHeader(sb);
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[McpServerResourceType]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var serviceType = ResolveServiceType(controller);

        foreach (var action in actions)
        {
            EmitResourceWrapper(sb, controller, action, serviceType, entity, syntaxIndex);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitResourceWrapper(
        StringBuilder sb,
        Type controller,
        AnnotatedAction action,
        Type? serviceType,
        McpEntityInfo? entity,
        ControllerSyntaxIndex syntaxIndex)
    {
        var method = action.Method;
        var attr = action.ResourceAttribute!;

        var uriTemplate = attr.UriTemplate;
        if (string.IsNullOrWhiteSpace(uriTemplate))
            throw new InvalidOperationException(
                $"{controller.Name}.{method.Name}: [ExposeAsMcpResource] requires a UriTemplate.");

        var resourceName = !string.IsNullOrWhiteSpace(attr.Name)
            ? attr.Name!
            : $"{ToSnakeCase(entity!.Singular)}_{ToSnakeCase(method.Name)}";

        var mimeType = attr.MimeType ?? "application/json";

        var description = ResolveDescription(method, attr.Instructions, entity!);
        var unwrapped = UnwrapActionResultType(method.ReturnType);
        var isString = unwrapped == typeof(string);

        sb.AppendLine($"    [McpServerResource(UriTemplate = \"{uriTemplate}\", Name = \"{resourceName}\", MimeType = \"{mimeType}\")]");
        sb.AppendLine($"    [Description(@\"{EscapeForVerbatim(description)}\")]");

        var serviceParam = serviceType is not null
            ? $"{FormatType(serviceType)} service"
            : "/* service-not-resolved */ object service";

        var actionParams = method.GetParameters()
            .Select(p => $"[Description(@\"{EscapeForVerbatim(ResolveParamDoc(method, p.Name!, entity!))}\")] {FormatParameterType(p)} {p.Name}")
            .ToList();

        var allParams = new List<string> { serviceParam };
        allParams.AddRange(actionParams);
        var paramList = string.Join(",\n        ", allParams);

        var argList = string.Join(", ", method.GetParameters().Select(p => p.Name));
        var serviceCall = ExtractServiceCall(method, syntaxIndex) ?? $"{method.Name}({argList})";

        var methodName = ToPascalCase(resourceName);
        sb.AppendLine($"    public static async System.Threading.Tasks.Task<string> {methodName}(");
        sb.AppendLine($"        {paramList})");
        if (isString)
        {
            sb.AppendLine($"        => await service.{serviceCall};");
        }
        else
        {
            sb.AppendLine($"        => System.Text.Json.JsonSerializer.Serialize(await service.{serviceCall});");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Unwraps <c>Task&lt;ActionResult&lt;T&gt;&gt;</c> → <c>T</c>, and <c>Task&lt;T&gt;</c> → <c>T</c>.
    /// Returns null for non-Task returns.
    /// </summary>
    private static Type? UnwrapActionResultType(Type returnType)
    {
        if (!returnType.IsGenericType || returnType.GetGenericTypeDefinition() != typeof(Task<>)) return null;
        var inner = returnType.GetGenericArguments()[0];
        if (inner.IsGenericType && inner.GetGenericTypeDefinition() == typeof(ActionResult<>))
            return inner.GetGenericArguments()[0];
        return inner;
    }

    private static string EmitSurface(Type controller, List<AnnotatedAction> actions, McpEntityInfo? entity, ControllerSyntaxIndex syntaxIndex)
    {
        var ns = controller.Namespace!;
        var className = $"{controller.Name}McpSurface";
        var sb = new StringBuilder();
        EmitHeader(sb);
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[McpServerToolType]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var serviceType = ResolveServiceType(controller);

        foreach (var action in actions.Where(a => a.ToolAttribute is not null))
        {
            EmitToolWrapper(sb, controller, action, serviceType, entity, syntaxIndex);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Best-effort discovery of the service the controller delegates to. For
    /// <c>GenericCrudController</c>-derived controllers the service is the 7th type argument
    /// (<c>TService</c>). Returns null when no obvious service is found — the caller falls back
    /// to a placeholder that the developer is expected to fill in.
    /// </summary>
    private static Type? ResolveServiceType(Type controller)
    {
        for (var t = controller; t is not null; t = t.BaseType)
        {
            if (t.IsGenericType && StripArity(t.Name) == "GenericCrudController")
            {
                var args = t.GetGenericArguments();
                if (args.Length >= 7) return args[6]; // TService is the 7th type parameter
            }
        }

        // Fallback: standalone controllers expose `protected readonly TService Service;`
        // (or property) — match by the conventional name "Service".
        const BindingFlags anyInstanceDeclared = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly;
        for (var t = controller; t is not null; t = t.BaseType)
        {
            if (t.GetField("Service", anyInstanceDeclared) is { } field) return field.FieldType;
            if (t.GetProperty("Service", anyInstanceDeclared) is { } property) return property.PropertyType;
        }
        return null;
    }

    private static void EmitToolWrapper(
        StringBuilder sb,
        Type controller,
        AnnotatedAction action,
        Type? serviceType,
        McpEntityInfo? entity,
        ControllerSyntaxIndex syntaxIndex)
    {
        var method = action.Method;
        var toolName = ResolveToolName(controller, method, action.ToolAttribute, entity);
        var description = ResolveDescription(method, action.ToolAttribute?.Instructions, entity!);
        var returnTypeText = EmitReturnType(method);

        sb.AppendLine($"    [McpServerTool(Name = \"{toolName}\")]");
        sb.AppendLine($"    [Description(@\"{EscapeForVerbatim(description)}\")]");

        var serviceParam = serviceType is not null
            ? $"{FormatType(serviceType)} service"
            : "/* service-not-resolved */ object service";

        var actionParams = method.GetParameters()
            .Select(p => $"[Description(@\"{EscapeForVerbatim(ResolveParamDoc(method, p.Name!, entity!))}\")] {FormatParameterType(p)} {p.Name}")
            .ToList();

        var allParams = new List<string> { serviceParam };
        allParams.AddRange(actionParams);

        var paramList = string.Join(",\n        ", allParams);
        var argList = string.Join(", ", method.GetParameters().Select(p => p.Name));

        // Mirror the literal `Service.X(args)` call from the controller body rather than passing
        // controller args through verbatim — controller and service signatures don't always agree
        // on argument order.
        var serviceCall = ExtractServiceCall(method, syntaxIndex) ?? $"{method.Name}({argList})";

        sb.AppendLine($"    public static {returnTypeText} {ToPascalCase(toolName)}(");
        sb.AppendLine($"        {paramList})");
        sb.AppendLine($"        => service.{serviceCall};");
        sb.AppendLine();
    }

    /// <summary>
    /// Finds the literal `Service.Foo(...)` call for the action via the syntax index, walking the
    /// override chain so a derived controller can override an inherited action purely to add a richer
    /// summary (body: <c>=> base.X(...)</c>) — the service call is then resolved from the base method.
    /// </summary>
    private static string? ExtractServiceCall(MethodInfo method, ControllerSyntaxIndex syntaxIndex)
    {
        var parameterCount = method.GetParameters().Length;
        for (var m = method; m is not null; m = OverriddenMethod(m))
        {
            var found = syntaxIndex.TryExtractServiceCall(StripArity(m.DeclaringType!.Name), m.Name, parameterCount);
            if (found is not null) return found;
        }
        return null;
    }

    private static MethodInfo? OverriddenMethod(MethodInfo method)
    {
        var baseDefinition = method.GetBaseDefinition();
        if (baseDefinition == method) return null;

        for (var t = method.DeclaringType?.BaseType; t is not null; t = t.BaseType)
        {
            var candidate = t
                .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                .FirstOrDefault(m => m.Name == method.Name && m.GetBaseDefinition() == baseDefinition);
            if (candidate is not null) return candidate;
        }
        return null;
    }

    /// <summary>
    /// Turns the controller action's return type into the MCP wrapper's return type string.
    /// Patterns:
    ///   <c>Task&lt;ActionResult&lt;T&gt;&gt;</c> → <c>Task&lt;T&gt;</c>
    ///   <c>Task&lt;IActionResult&gt;</c>          → <c>Task</c>   (best-effort; agent gets no payload)
    ///   <c>Task&lt;T&gt;</c>                       → <c>Task&lt;T&gt;</c>  (unchanged)
    ///   <c>ActionResult&lt;T&gt;</c>               → <c>Task&lt;T&gt;</c>
    ///   <c>T</c>                                   → <c>Task&lt;T&gt;</c>  (wrap)
    /// </summary>
    private static string EmitReturnType(MethodInfo method)
    {
        var returnType = method.ReturnType;
        var nullability = new NullabilityInfoContext().Create(method.ReturnParameter);

        if (returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(Task<>))
        {
            var inner = returnType.GetGenericArguments()[0];
            var innerNullability = Argument(nullability, 0);
            if (inner.IsGenericType && inner.GetGenericTypeDefinition() == typeof(ActionResult<>))
                return $"System.Threading.Tasks.Task<{FormatType(inner.GetGenericArguments()[0], Argument(innerNullability, 0))}>";
            if (inner == typeof(IActionResult))
                return "System.Threading.Tasks.Task";
            return $"System.Threading.Tasks.Task<{FormatType(inner, innerNullability)}>";
        }
        if (returnType.IsGenericType && returnType.GetGenericTypeDefinition() == typeof(ActionResult<>))
            return $"System.Threading.Tasks.Task<{FormatType(returnType.GetGenericArguments()[0], Argument(nullability, 0))}>";
        if (returnType == typeof(IActionResult))
            return "System.Threading.Tasks.Task";
        return $"System.Threading.Tasks.Task<{FormatType(returnType, nullability)}>";
    }

    private static string ResolveToolName(Type controller, MethodInfo method, ExposeAsMcpToolAttribute? attr, McpEntityInfo? entity)
    {
        if (!string.IsNullOrWhiteSpace(attr?.Name)) return attr.Name!;

        // Default convention: {Entity.Plural ?? controller-name-without-Controller}_{methodName} in snake_case
        var noun = entity?.Plural ?? StripControllerSuffix(controller.Name);
        return $"{ToSnakeCase(noun)}_{ToSnakeCase(method.Name)}";
    }

    /// <summary>
    /// The wrapper's [Description]: the action's summary ([EndpointSummary] override, else the
    /// <see cref="EndpointDocConvention"/> text), with the annotation's <c>Instructions</c>
    /// appended when set.
    /// </summary>
    private static string ResolveDescription(MethodInfo method, string? instructions, McpEntityInfo entity)
    {
        var summary = ResolveEndpointSummary(method)
            ?? EndpointDocConvention.Summary(method.Name, entity.Singular, entity.Plural)
            ?? string.Empty;

        return string.IsNullOrWhiteSpace(instructions)
            ? summary
            : $"{summary}\n\n{instructions}";
    }

    private static string? ResolveEndpointSummary(MethodInfo method)
    {
        for (var m = method; m is not null; m = OverriddenMethod(m))
        {
            var attr = m.GetCustomAttribute<EndpointSummaryAttribute>(inherit: false);
            if (attr?.Summary is { Length: > 0 } summary)
                return summary;
        }
        return null;
    }

    private static string ResolveParamDoc(MethodInfo method, string paramName, McpEntityInfo entity)
    {
        var parameter = method.GetParameters().FirstOrDefault(p => p.Name == paramName);
        var overrideAttr = parameter?.GetCustomAttribute<System.ComponentModel.DescriptionAttribute>(inherit: false);
        if (overrideAttr?.Description is { Length: > 0 } description)
            return description;

        return EndpointDocConvention.ParamDescription(paramName, method.Name, entity.Singular) ?? paramName;
    }

    // ---------------------------------------------------------------------------
    // C# type-name formatting — the reflection replacement for ITypeSymbol.ToDisplayString().
    // Ground truth is the committed .g.cs corpus: special types print as keywords (string),
    // everything else fully qualified (System.Guid), Nullable<T> as T?, and nullable reference
    // annotations (Dto?) recovered via NullabilityInfoContext.
    // ---------------------------------------------------------------------------

    private static readonly Dictionary<Type, string> TypeKeywords = new()
    {
        [typeof(string)] = "string",
        [typeof(object)] = "object",
        [typeof(bool)] = "bool",
        [typeof(byte)] = "byte",
        [typeof(sbyte)] = "sbyte",
        [typeof(short)] = "short",
        [typeof(ushort)] = "ushort",
        [typeof(int)] = "int",
        [typeof(uint)] = "uint",
        [typeof(long)] = "long",
        [typeof(ulong)] = "ulong",
        [typeof(char)] = "char",
        [typeof(double)] = "double",
        [typeof(float)] = "float",
        [typeof(decimal)] = "decimal",
        [typeof(void)] = "void",
    };

    private static string FormatParameterType(ParameterInfo parameter)
    {
        return FormatType(parameter.ParameterType, new NullabilityInfoContext().Create(parameter));
    }

    private static string FormatType(Type type, NullabilityInfo? nullability = null)
    {
        if (Nullable.GetUnderlyingType(type) is { } underlying)
            return FormatType(underlying) + "?";

        var suffix = !type.IsValueType && nullability is { ReadState: NullabilityState.Nullable } ? "?" : "";

        if (type.IsArray)
            return FormatType(type.GetElementType()!, nullability?.ElementType) + "[]" + suffix;

        if (TypeKeywords.TryGetValue(type, out var keyword))
            return keyword + suffix;

        if (type.IsGenericType)
        {
            var args = type.GetGenericArguments();
            var argTexts = args.Select((a, i) => FormatType(a, Argument(nullability, i)));
            return $"{QualifiedName(type)}<{string.Join(", ", argTexts)}>{suffix}";
        }

        return QualifiedName(type) + suffix;
    }

    private static NullabilityInfo? Argument(NullabilityInfo? nullability, int index)
    {
        return nullability is not null && index < nullability.GenericTypeArguments.Length
            ? nullability.GenericTypeArguments[index]
            : null;
    }

    private static string QualifiedName(Type type)
    {
        var name = StripArity(type.Name);
        if (type.IsNested && type.DeclaringType is { } declaring)
            return $"{QualifiedName(declaring)}.{name}";
        return type.Namespace is { Length: > 0 } ns ? $"{ns}.{name}" : name;
    }

    private static string StripArity(string name)
    {
        var backtick = name.IndexOf('`');
        return backtick < 0 ? name : name[..backtick];
    }

    private static string StripControllerSuffix(string name) =>
        name.EndsWith("Controller", StringComparison.Ordinal)
            ? name.Substring(0, name.Length - "Controller".Length)
            : name;

    private static string ToSnakeCase(string s)
    {
        var sb = new StringBuilder();
        var lastWasSeparator = true;
        for (var i = 0; i < s.Length; i++)
        {
            var c = s[i];
            if (c == ' ' || c == '-' || c == '_')
            {
                if (!lastWasSeparator) sb.Append('_');
                lastWasSeparator = true;
                continue;
            }
            if (i > 0 && char.IsUpper(c) && !lastWasSeparator) sb.Append('_');
            sb.Append(char.ToLowerInvariant(c));
            lastWasSeparator = false;
        }
        return sb.ToString();
    }

    private static string ToPascalCase(string snakeCase)
    {
        var parts = snakeCase.Split('_');
        var sb = new StringBuilder();
        foreach (var p in parts)
        {
            if (p.Length == 0) continue;
            sb.Append(char.ToUpperInvariant(p[0]));
            if (p.Length > 1) sb.Append(p.Substring(1));
        }
        return sb.ToString();
    }

    private static string EscapeForVerbatim(string s) => s.Replace("\"", "\"\"");

    private sealed record AnnotatedAction(MethodInfo Method, ExposeAsMcpToolAttribute? ToolAttribute, ExposeAsMcpResourceAttribute? ResourceAttribute);
    private sealed record McpEntityInfo(string Singular, string Plural);
}
