// SPDX-License-Identifier: LicenseRef-Snap-CD-Source-Available-1.1
// Copyright (c) 2026 Karl Schriek / Schrieksoft.
// No license is granted to use this file, in whole or in part, (a) as training, fine-tuning, retrieval, or
// embedding data for any machine-learning model, or (b) as input to any machine-learning model, agent, or automated
// system for the purpose of producing a derivative work or reimplementation that is not otherwise permitted by the
// Snap CD Source-Available License (including any Competing Product as defined therein). Contact info@snapcd.io
// for terms covering either use.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SnapCd.Contracts;

namespace SnapCd.Mcp.Generator;

/// <summary>
/// Codegen that emits MCP tool / resource wrappers for every controller action annotated with
/// <c>[ExposeAsMcpTool]</c> or <c>[ExposeAsMcpResource]</c>. Driven by <see cref="Program"/> as a
/// one-shot CLI — writes <c>&lt;ControllerName&gt;McpSurface.cs</c> files into a tracked output
/// folder under the target project.
///
/// Discovery:
///   - Walks every <see cref="INamedTypeSymbol"/> in the loaded compilation that derives (directly or
///     transitively) from <c>ControllerBase</c>.
///   - For each, collects action methods marked with <c>[ExposeAsMcpTool]</c> / <c>[ExposeAsMcpResource]</c>
///     — including methods inherited from a generic base controller (e.g. <c>GenericCrudController</c>).
///   - The derived controller's <c>[McpEntity]</c> attribute supplies the entity name for the
///     convention-derived descriptions (<see cref="EndpointDocConvention"/>); an [EndpointSummary]
///     on the action overrides the convention, and the annotation's <c>Instructions</c> is appended.
/// </summary>
public static class McpSurfaceEmitter
{
    private const string ExposeToolAttribute = "SnapCd.Contracts.Mcp.ExposeAsMcpToolAttribute";
    private const string ExposeResourceAttribute = "SnapCd.Contracts.Mcp.ExposeAsMcpResourceAttribute";
    private const string EntityAttribute = "SnapCd.Contracts.Mcp.McpEntityAttribute";
    private const string EndpointSummaryAttribute = "Microsoft.AspNetCore.Http.EndpointSummaryAttribute";

    /// <summary>
    /// SnapCd license header + auto-generated banner. Prepended to every generated <c>*.g.cs</c>
    /// file because pre-commit's license-header check skips <c>.g.cs</c> (assumes they're
    /// generated-and-already-headed), so the codegen owns the header itself.
    /// </summary>
    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("// SPDX-License-Identifier: LicenseRef-Snap-CD-Source-Available-1.1");
        sb.AppendLine("// Copyright (c) 2026 Karl Schriek / Schrieksoft.");
        sb.AppendLine("// No license is granted to use this file, in whole or in part, (a) as training, fine-tuning, retrieval, or");
        sb.AppendLine("// embedding data for any machine-learning model, or (b) as input to any machine-learning model, agent, or automated");
        sb.AppendLine("// system for the purpose of producing a derivative work or reimplementation that is not otherwise permitted by the");
        sb.AppendLine("// Snap CD Source-Available License (including any Competing Product as defined therein). Contact info@snapcd.io");
        sb.AppendLine("// for terms covering either use.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by SnapCd.Mcp.Generator. Re-run `dotnet run --project SnapCd.Mcp.Generator`");
        sb.AppendLine("// after changing controller annotations or [EndpointSummary] texts. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using ModelContextProtocol.Server;");
        sb.AppendLine();
    }

    public sealed record GeneratedFile(string FileName, string Source);

    /// <summary>
    /// Walks the compilation, finds every concrete annotated controller, and yields a
    /// <see cref="GeneratedFile"/> for each. The caller writes them to disk.
    /// </summary>
    public static IEnumerable<GeneratedFile> Emit(Compilation compilation)
    {
        foreach (var controller in EnumerateControllers(compilation))
        {
            if (controller.IsAbstract) continue;
            if (controller.IsGenericType) continue;

            // Require [McpEntity] as the explicit opt-in. Without it, a derived controller that
            // inherits annotated actions from a generic base would still be auto-exposed —
            // bypassing the safety of opt-in.
            var entity = ResolveEntity(controller);
            if (entity is null) continue;

            var actions = CollectAnnotatedActions(controller).ToList();
            var toolActions = actions.Where(a => a.ToolAttribute is not null).ToList();
            var resourceActions = actions.Where(a => a.ResourceAttribute is not null).ToList();

            if (toolActions.Count > 0)
                yield return new GeneratedFile(
                    $"{controller.Name}McpSurface.g.cs",
                    EmitSurface(controller, toolActions, entity));

            if (resourceActions.Count > 0)
                yield return new GeneratedFile(
                    $"{controller.Name}McpResourceSurface.g.cs",
                    EmitResourceSurface(controller, resourceActions, entity));
        }
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateControllers(Compilation compilation)
    {
        foreach (var tree in compilation.SyntaxTrees)
        {
            var model = compilation.GetSemanticModel(tree);
            foreach (var cd in tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                if (cd.BaseList is null) continue;
                if (model.GetDeclaredSymbol(cd) is not INamedTypeSymbol symbol) continue;
                if (!InheritsFromControllerBase(symbol)) continue;
                yield return symbol;
            }
        }
    }

    private static bool InheritsFromControllerBase(INamedTypeSymbol type)
    {
        for (var t = type.BaseType; t is not null; t = t.BaseType)
        {
            if (t.Name == "ControllerBase" && t.ContainingNamespace?.ToDisplayString() == "Microsoft.AspNetCore.Mvc")
                return true;
        }
        return false;
    }

    /// <summary>
    /// Walks the inheritance chain and collects every method annotated with
    /// <c>[ExposeAsMcpTool]</c> or <c>[ExposeAsMcpResource]</c>.
    /// </summary>
    private static IEnumerable<AnnotatedAction> CollectAnnotatedActions(INamedTypeSymbol controller)
    {
        var seen = new HashSet<string>();
        for (var t = controller; t is not null; t = t.BaseType)
        {
            foreach (var member in t.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind != MethodKind.Ordinary) continue;
                if (member.DeclaredAccessibility != Accessibility.Public) continue;
                if (!seen.Add(member.Name)) continue; // a derived override masks the base

                var toolAttr = member.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == ExposeToolAttribute);
                var resourceAttr = member.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == ExposeResourceAttribute);
                if (toolAttr is null && resourceAttr is null) continue;

                yield return new AnnotatedAction(member, toolAttr, resourceAttr);
            }
        }
    }

    private static McpEntityInfo? ResolveEntity(INamedTypeSymbol controller)
    {
        for (var t = controller; t is not null; t = t.BaseType)
        {
            var attr = t.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == EntityAttribute);
            if (attr is null) continue;
            var singular = attr.NamedArguments.FirstOrDefault(n => n.Key == "Singular").Value.Value as string;
            var plural = attr.NamedArguments.FirstOrDefault(n => n.Key == "Plural").Value.Value as string;
            if (singular is null || plural is null) continue;
            return new McpEntityInfo(singular, plural);
        }
        return null;
    }

    private static string EmitResourceSurface(INamedTypeSymbol controller, List<AnnotatedAction> actions, McpEntityInfo? entity)
    {
        var ns = controller.ContainingNamespace.ToDisplayString();
        var className = $"{controller.Name}McpResourceSurface";
        var sb = new StringBuilder();
        EmitHeader(sb);
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[McpServerResourceType]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var serviceType = ResolveServiceType(controller);

        foreach (var action in actions)
        {
            EmitResourceWrapper(sb, controller, action, serviceType, entity);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitResourceWrapper(
        StringBuilder sb,
        INamedTypeSymbol controller,
        AnnotatedAction action,
        ITypeSymbol? serviceType,
        McpEntityInfo? entity)
    {
        var method = action.Method;
        var attr = action.ResourceAttribute!;

        var uriTemplate = attr.NamedArguments.FirstOrDefault(n => n.Key == "UriTemplate").Value.Value as string;
        if (string.IsNullOrWhiteSpace(uriTemplate))
            throw new System.InvalidOperationException(
                $"{controller.Name}.{method.Name}: [ExposeAsMcpResource] requires a UriTemplate.");

        var explicitName = attr.NamedArguments.FirstOrDefault(n => n.Key == "Name").Value.Value as string;
        var resourceName = !string.IsNullOrWhiteSpace(explicitName)
            ? explicitName!
            : $"{ToSnakeCase(entity!.Singular)}_{ToSnakeCase(method.Name)}";

        var mimeType = attr.NamedArguments.FirstOrDefault(n => n.Key == "MimeType").Value.Value as string
            ?? "application/json";

        var description = ResolveDescription(method, attr, entity!);
        var unwrapped = UnwrapActionResultType(method.ReturnType);
        var isString = unwrapped?.SpecialType == SpecialType.System_String;

        sb.AppendLine($"    [McpServerResource(UriTemplate = \"{uriTemplate}\", Name = \"{resourceName}\", MimeType = \"{mimeType}\")]");
        sb.AppendLine($"    [Description(@\"{EscapeForVerbatim(description)}\")]");

        var serviceParam = serviceType is not null
            ? $"{serviceType.ToDisplayString()} service"
            : "/* service-not-resolved */ object service";

        var actionParams = method.Parameters
            .Select(p => $"[Description(@\"{EscapeForVerbatim(ResolveParamDoc(method, p.Name, entity!))}\")] {p.Type.ToDisplayString()} {p.Name}")
            .ToList();

        var allParams = new List<string> { serviceParam };
        allParams.AddRange(actionParams);
        var paramList = string.Join(",\n        ", allParams);

        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));
        var serviceCall = ExtractServiceCall(method) ?? $"{method.Name}({argList})";

        var methodName = ToPascalCase(resourceName);
        sb.AppendLine($"    public static async System.Threading.Tasks.Task<string> {methodName}(");
        sb.AppendLine($"        {paramList})");
        if (isString)
        {
            sb.AppendLine($"        => await service.{serviceCall};");
        }
        else
        {
            sb.AppendLine($"        => System.Text.Json.JsonSerializer.Serialize(await service.{serviceCall});");
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Unwraps <c>Task&lt;ActionResult&lt;T&gt;&gt;</c> → <c>T</c>, and <c>Task&lt;T&gt;</c> → <c>T</c>.
    /// Returns null for non-Task returns.
    /// </summary>
    private static ITypeSymbol? UnwrapActionResultType(ITypeSymbol returnType)
    {
        if (returnType is not INamedTypeSymbol named) return null;
        if (!named.IsGenericType || named.Name != "Task" || named.TypeArguments.Length != 1) return null;
        var inner = named.TypeArguments[0];
        if (inner is INamedTypeSymbol innerNamed
            && innerNamed.IsGenericType
            && innerNamed.Name == "ActionResult"
            && innerNamed.TypeArguments.Length == 1)
        {
            return innerNamed.TypeArguments[0];
        }
        return inner;
    }

    private static string EmitSurface(INamedTypeSymbol controller, List<AnnotatedAction> actions, McpEntityInfo? entity)
    {
        var ns = controller.ContainingNamespace.ToDisplayString();
        var className = $"{controller.Name}McpSurface";
        var sb = new StringBuilder();
        EmitHeader(sb);
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[McpServerToolType]");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var serviceType = ResolveServiceType(controller);

        foreach (var action in actions.Where(a => a.ToolAttribute is not null))
        {
            EmitToolWrapper(sb, controller, action, serviceType, entity);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Best-effort discovery of the service the controller delegates to. For
    /// <c>GenericCrudController</c>-derived controllers the service is the 7th type argument
    /// (<c>TService</c>). Returns null when no obvious service is found — the caller falls back
    /// to a placeholder that the developer is expected to fill in.
    /// </summary>
    private static ITypeSymbol? ResolveServiceType(INamedTypeSymbol controller)
    {
        for (var t = controller; t is not null; t = t.BaseType)
        {
            if (t.IsGenericType && t.OriginalDefinition.Name == "GenericCrudController")
            {
                var args = t.TypeArguments;
                if (args.Length >= 7) return args[6]; // TService is the 7th type parameter
            }
        }

        // Fallback: standalone controllers expose `protected readonly TService Service;`
        // (or property) — match by the conventional name "Service".
        for (var t = controller; t is not null; t = t.BaseType)
        {
            foreach (var member in t.GetMembers("Service"))
            {
                if (member is IFieldSymbol f) return f.Type;
                if (member is IPropertySymbol p) return p.Type;
            }
        }
        return null;
    }

    private static void EmitToolWrapper(
        StringBuilder sb,
        INamedTypeSymbol controller,
        AnnotatedAction action,
        ITypeSymbol? serviceType,
        McpEntityInfo? entity)
    {
        var method = action.Method;
        var toolName = ResolveToolName(controller, method, action.ToolAttribute, entity);
        var description = ResolveDescription(method, action.ToolAttribute, entity!);
        var returnTypeText = EmitReturnType(method.ReturnType);

        sb.AppendLine($"    [McpServerTool(Name = \"{toolName}\")]");
        sb.AppendLine($"    [Description(@\"{EscapeForVerbatim(description)}\")]");

        var serviceParam = serviceType is not null
            ? $"{serviceType.ToDisplayString()} service"
            : "/* service-not-resolved */ object service";

        var actionParams = method.Parameters
            .Select(p => $"[Description(@\"{EscapeForVerbatim(ResolveParamDoc(method, p.Name, entity!))}\")] {p.Type.ToDisplayString()} {p.Name}")
            .ToList();

        var allParams = new List<string> { serviceParam };
        allParams.AddRange(actionParams);

        var paramList = string.Join(",\n        ", allParams);
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));

        // Parse the controller method body to find the actual `Service.X(args)` call. Controller
        // and service signatures don't always agree on argument order — e.g. controller's
        // `Update(orgId, dto, id)` calls `Service.Update(dto, id, orgId)`. We mirror the literal
        // call from the controller body rather than passing controller args through verbatim.
        var serviceCall = ExtractServiceCall(method) ?? $"{method.Name}({argList})";

        sb.AppendLine($"    public static {returnTypeText} {ToPascalCase(toolName)}(");
        sb.AppendLine($"        {paramList})");
        sb.AppendLine($"        => service.{serviceCall};");
        sb.AppendLine();
    }

    /// <summary>
    /// Walks the controller method's syntax body to find the literal `Service.Foo(arg1, arg2, ...)`
    /// or `await Service.Foo(...)` call, returning <c>Foo(arg1, arg2)</c> as a string. Returns null
    /// if no `Service.{Method}` invocation is found (fallback: assume same arg order as the controller).
    /// Walks the override chain so a derived controller can override an inherited action purely
    /// to add a richer XML doc summary (body: <c>=> base.X(...)</c>) — the service call is then
    /// resolved from the base method's body.
    /// </summary>
    private static string? ExtractServiceCall(IMethodSymbol method)
    {
        for (var m = method; m is not null; m = m.OverriddenMethod)
        {
            var found = TryExtractFromMethod(m);
            if (found is not null) return found;
        }
        return null;
    }

    private static string? TryExtractFromMethod(IMethodSymbol method)
    {
        foreach (var declRef in method.DeclaringSyntaxReferences)
        {
            if (declRef.GetSyntax() is not MethodDeclarationSyntax mds) continue;
            foreach (var invocation in mds.DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (invocation.Expression is MemberAccessExpressionSyntax mae
                    && mae.Expression is IdentifierNameSyntax id
                    && id.Identifier.Text == "Service")
                {
                    var calledName = mae.Name.Identifier.Text;
                    var args = invocation.ArgumentList.Arguments
                        .Select(a => a.ToFullString().Trim());
                    return $"{calledName}({string.Join(", ", args)})";
                }
            }
        }
        return null;
    }

    /// <summary>
    /// Turns the controller action's return type into the MCP wrapper's return type string.
    /// Patterns:
    ///   <c>Task&lt;ActionResult&lt;T&gt;&gt;</c> → <c>Task&lt;T&gt;</c>
    ///   <c>Task&lt;IActionResult&gt;</c>          → <c>Task</c>   (best-effort; agent gets no payload)
    ///   <c>Task&lt;T&gt;</c>                       → <c>Task&lt;T&gt;</c>  (unchanged)
    ///   <c>ActionResult&lt;T&gt;</c>               → <c>Task&lt;T&gt;</c>
    ///   <c>T</c>                                   → <c>Task&lt;T&gt;</c>  (wrap)
    /// </summary>
    private static string EmitReturnType(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol named)
        {
            if (named.IsGenericType && named.Name == "Task" && named.TypeArguments.Length == 1)
            {
                var inner = named.TypeArguments[0];
                if (inner is INamedTypeSymbol innerNamed)
                {
                    if (innerNamed.IsGenericType && innerNamed.Name == "ActionResult" && innerNamed.TypeArguments.Length == 1)
                        return $"System.Threading.Tasks.Task<{innerNamed.TypeArguments[0].ToDisplayString()}>";
                    if (innerNamed.Name == "IActionResult")
                        return "System.Threading.Tasks.Task";
                }
                return $"System.Threading.Tasks.Task<{inner.ToDisplayString()}>";
            }
            if (named.IsGenericType && named.Name == "ActionResult" && named.TypeArguments.Length == 1)
                return $"System.Threading.Tasks.Task<{named.TypeArguments[0].ToDisplayString()}>";
            if (named.Name == "IActionResult")
                return "System.Threading.Tasks.Task";
        }
        return $"System.Threading.Tasks.Task<{returnType.ToDisplayString()}>";
    }

    private static string ResolveToolName(INamedTypeSymbol controller, IMethodSymbol method, AttributeData? attr, McpEntityInfo? entity)
    {
        if (attr is not null)
        {
            var explicitName = attr.NamedArguments.FirstOrDefault(n => n.Key == "Name").Value.Value as string;
            if (!string.IsNullOrWhiteSpace(explicitName)) return explicitName!;
        }

        // Default convention: {Entity.Plural ?? controller-name-without-Controller}_{methodName} in snake_case
        var noun = entity?.Plural ?? StripControllerSuffix(controller.Name);
        return $"{ToSnakeCase(noun)}_{ToSnakeCase(method.Name)}";
    }

    /// <summary>
    /// The wrapper's [Description]: the action's summary ([EndpointSummary] override, else the
    /// <see cref="EndpointDocConvention"/> text), with the annotation's <c>Instructions</c>
    /// appended when set.
    /// </summary>
    private static string ResolveDescription(IMethodSymbol method, AttributeData? attr, McpEntityInfo entity)
    {
        var summary = ResolveEndpointSummary(method)
            ?? EndpointDocConvention.Summary(method.Name, entity.Singular, entity.Plural)
            ?? string.Empty;

        var instructions = attr?.NamedArguments.FirstOrDefault(n => n.Key == "Instructions").Value.Value as string;
        return string.IsNullOrWhiteSpace(instructions)
            ? summary
            : $"{summary}\n\n{instructions}";
    }

    private static string? ResolveEndpointSummary(IMethodSymbol method)
    {
        for (var m = method; m is not null; m = m.OverriddenMethod)
        {
            var attr = m.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == EndpointSummaryAttribute);
            if (attr?.ConstructorArguments.FirstOrDefault().Value is string summary && summary.Length > 0)
                return summary;
        }
        return null;
    }

    private static string ResolveParamDoc(IMethodSymbol method, string paramName, McpEntityInfo entity)
    {
        var parameter = method.Parameters.FirstOrDefault(p => p.Name == paramName);
        var overrideAttr = parameter?.GetAttributes().FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DescriptionAttribute");
        if (overrideAttr?.ConstructorArguments.FirstOrDefault().Value is string description && description.Length > 0)
            return description;

        return EndpointDocConvention.ParamDescription(paramName, method.Name, entity.Singular) ?? paramName;
    }

    private static string StripControllerSuffix(string name) =>
        name.EndsWith("Controller", System.StringComparison.Ordinal)
            ? name.Substring(0, name.Length - "Controller".Length)
            : name;

    private static string ToSnakeCase(string s)
    {
        var sb = new StringBuilder();
        var lastWasSeparator = true;
        for (var i = 0; i < s.Length; i++)
        {
            var c = s[i];
            if (c == ' ' || c == '-' || c == '_')
            {
                if (!lastWasSeparator) sb.Append('_');
                lastWasSeparator = true;
                continue;
            }
            if (i > 0 && char.IsUpper(c) && !lastWasSeparator) sb.Append('_');
            sb.Append(char.ToLowerInvariant(c));
            lastWasSeparator = false;
        }
        return sb.ToString();
    }

    private static string ToPascalCase(string snakeCase)
    {
        var parts = snakeCase.Split('_');
        var sb = new StringBuilder();
        foreach (var p in parts)
        {
            if (p.Length == 0) continue;
            sb.Append(char.ToUpperInvariant(p[0]));
            if (p.Length > 1) sb.Append(p.Substring(1));
        }
        return sb.ToString();
    }

    private static string EscapeForVerbatim(string s) => s.Replace("\"", "\"\"");

    private sealed record AnnotatedAction(IMethodSymbol Method, AttributeData? ToolAttribute, AttributeData? ResourceAttribute);
    private sealed record McpEntityInfo(string Singular, string Plural);
}
