using SnapCd.Contracts.Dto.RoleAssignments;
using SnapCd.Server.Core.Events.Repository.Organization.Base;

namespace SnapCd.Server.Core.Events.Repository.Organization;

public class ServicePrincipalNamespaceRoleAssignmentCreatedEvent : CreatedEvent<ServicePrincipalNamespaceRoleAssignmentReadDto>;

public class ServicePrincipalNamespaceRoleAssignmentUpdatedEvent : UpdatedEvent<ServicePrincipalNamespaceRoleAssignmentReadDto>;

public class ServicePrincipalNamespaceRoleAssignmentDeletedEvent : DeletedEvent<ServicePrincipalNamespaceRoleAssignmentReadDto>;
