using SnapCd.Contracts.Dto.RoleAssignments;
using SnapCd.Server.Core.Events.Repository.Organization.Base;

namespace SnapCd.Server.Core.Events.Repository.Organization;

public class ServicePrincipalModuleRoleAssignmentCreatedEvent : CreatedEvent<ServicePrincipalModuleRoleAssignmentReadDto>;

public class ServicePrincipalModuleRoleAssignmentUpdatedEvent : UpdatedEvent<ServicePrincipalModuleRoleAssignmentReadDto>;

public class ServicePrincipalModuleRoleAssignmentDeletedEvent : DeletedEvent<ServicePrincipalModuleRoleAssignmentReadDto>;
